apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "autonomous-meeting-assistant.fullname" . }}-backend
  labels:
    {{- include "autonomous-meeting-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "autonomous-meeting-assistant.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "autonomous-meeting-assistant.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        ports:
        - containerPort: {{ .Values.backend.service.port }}
        livenessProbe:
          httpGet:
            path: {{ .Values.backend.livenessProbe.path }}
            port: {{ .Values.backend.service.port }}
          initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.backend.readinessProbe.path }}
            port: {{ .Values.backend.service.port }}
          initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
        volumeMounts:
        - name: database-storage
          mountPath: /app/src/database
      volumes:
      - name: database-storage
        persistentVolumeClaim:
          claimName: {{ include "autonomous-meeting-assistant.fullname" . }}-backend-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "autonomous-meeting-assistant.fullname" . }}-backend
  labels:
    {{- include "autonomous-meeting-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "autonomous-meeting-assistant.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "autonomous-meeting-assistant.fullname" . }}-backend-pvc
  labels:
    {{- include "autonomous-meeting-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - {{ .Values.backend.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}


