apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "autonomous-meeting-assistant.fullname" . }}-frontend
  labels:
    {{- include "autonomous-meeting-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "autonomous-meeting-assistant.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "autonomous-meeting-assistant.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        ports:
        - containerPort: {{ .Values.frontend.service.port }}
        livenessProbe:
          httpGet:
            path: {{ .Values.frontend.livenessProbe.path }}
            port: {{ .Values.frontend.service.port }}
          initialDelaySeconds: {{ .Values.frontend.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.frontend.readinessProbe.path }}
            port: {{ .Values.frontend.service.port }}
          initialDelaySeconds: {{ .Values.frontend.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "autonomous-meeting-assistant.fullname" . }}-frontend
  labels:
    {{- include "autonomous-meeting-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "autonomous-meeting-assistant.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "autonomous-meeting-assistant.fullname" . }}-frontend
  labels:
    {{- include "autonomous-meeting-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    {{- toYaml .Values.frontend.ingress.annotations | nindent 4 }}
spec:
  rules:
  {{- range .Values.frontend.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ include "autonomous-meeting-assistant.fullname" $ }}-frontend
            port:
              number: {{ $.Values.frontend.service.port }}
      {{- end }}
  {{- end }}


